### ISSUE TITLE
code=exited, status=203/EXEC

### ISSUE THREAD

**Issue by joe-xing-ai** [aelassas/bookcars#2]
bookcars.service - BookCars API
   Loaded: loaded (/etc/systemd/system/bookcars.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2023-05-03 19:49:37 PDT; 10ms ago
  Process: 26827 ExecStart=/usr/bin/node -r dotenv/config app.js (code=exited, status=203/EXEC)
 Main PID: 26827 (code=exited, status=203/EXEC)
BookCars API deployed in 0 minutes and 3 seconds.
Deploying BookCars backend...

How do I debug this error when I was following your instructions for installation, thanks!

**Comment by aelassas** [comment]
You can check the logs in /var/log/bookcars.log
