### ISSUE TITLE
how to solve this error

### ISSUE THREAD

**Issue by Mayur2502** [aelassas/bookcars#42]
file:///E:/bookcars/api/server.js:18
const DB_SSL = process.env.BC_DB_SSL.toLowerCase() === 'true'
                                     ^

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at file:///E:/bookcars/api/server.js:18:38
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.16.1
[nodemon] app crashed - waiting for file changes before starting...

**Comment by aelassas** [comment]
First, check out the [prerequisites](https://github.com/aelassas/bookcars/wiki/Run-from-Source#prerequisites).

Then, you need to create `api/.env` file with the following content:
```
NODE_ENV=development
BC_PORT=4002
BC_HTTPS=false
BC_PRIVATE_KEY=/etc/ssl/bookcars.com.key
BC_CERTIFICATE=/etc/ssl/bookcars.com.crt
BC_DB_HOST=127.0.0.1
BC_DB_PORT=27017
BC_DB_SSL=false
BC_DB_SSL_KEY=/etc/ssl/bookcars.com.key
BC_DB_SSL_CERT=/etc/ssl/bookcars.com.crt
BC_DB_SSL_CA=/etc/ssl/bookcars.com.ca.pem
BC_DB_DEBUG=false
BC_DB_APP_NAME=bookcars
BC_DB_AUTH_SOURCE=admin
BC_DB_USERNAME=admin
BC_DB_PASSWORD=PASSWORD
BC_DB_NAME=bookcars
BC_JWT_SECRET=JWT_SECRET
BC_JWT_EXPIRE_AT=86400
BC_TOKEN_EXPIRE_AT=86400
BC_SMTP_HOST=in-v3.mailjet.com
BC_SMTP_PORT=587
BC_SMTP_USER=USER
BC_SMTP_PASS=PASSWORD
BC_SMTP_FROM=admin@bookcars.com
BC_ADMIN_EMAIL=admin@bookcars.com
BC_CDN_USERS=/var/www/cdn/bookcars/users
BC_CDN_TEMP_USERS=/var/www/cdn/bookcars/temp/users
BC_CDN_CARS=/var/www/cdn/bookcars/cars
BC_CDN_TEMP_CARS=/var/www/cdn/bookcars/temp/cars
BC_DEFAULT_LANGUAGE=en
BC_BACKEND_HOST=http://localhost:3001/
BC_FRONTEND_HOST=http://localhost:3002/
BC_MINIMUM_AGE=21
BC_EXPO_ACCESS_TOKEN=EXPO_ACCESS_TOKEN
```

Set the following options:
```
BC_DB_PASSWORD=PASSWORD
BC_JWT_SECRET=JWT_SECRET
BC_SMTP_HOST=in-v3.mailjet.com
BC_SMTP_PORT=587
BC_SMTP_USER=USER
BC_SMTP_PASS=PASSWORD
BC_SMTP_FROM=admin@bookcars.com
BC_ADMIN_EMAIL=admin@bookcars.com
```

Replace `PASSWORD` with a strong password of your choice and `JWT_SECRET` with a secret token. Finally, set the SMTP options. SMTP options are necessary for sign up.

If you are on Windows, you need to install IIS and update these settings as well:
```
BC_CDN_USERS=/var/www/cdn/bookcars/users
BC_CDN_TEMP_USERS=/var/www/cdn/bookcars/temp/users
BC_CDN_CARS=/var/www/cdn/bookcars/cars
BC_CDN_TEMP_CARS=/var/www/cdn/bookcars/temp/cars
```

Check out step 6 on this [documentation](https://github.com/aelassas/bookcars/wiki/Run-from-Source).

If you want to enable push notifications in the mobile app, follow these [instructions](https://github.com/aelassas/bookcars/wiki/Build-Mobile-App#configuration) and set the following option:
```
BC_EXPO_ACCESS_TOKEN=EXPO_ACCESS_TOKEN
```

Run the api:
```
cd ./api
npm install
npm run dev
```

For the backend and the frontend, you need to create .env file as well. You can find the instructions [here](https://github.com/aelassas/bookcars/wiki/Run-from-Source).

**Comment by Mayur2502** [comment]
I am trying to run the android app should I do the same and thank u so much
for replying

**Comment by aelassas** [comment]
You can find the instructions on how to run the mobile app [here](https://github.com/aelassas/bookcars/wiki/Run-Mobile-App).
