### ISSUE TITLE
make the dockerfile available in GIT :-)

### ISSUE THREAD

**Issue by beankylla** [aelassas/bookcars#45]
Hello,

For noobies that are afraid to go forward would it be possible to have the dockerfile here in github?

**Comment by aelassas** [comment]
Dockerfiles are already available in the git repository:

- api: https://github.com/aelassas/bookcars/blob/main/api/Dockerfile
- backend: https://github.com/aelassas/bookcars/blob/main/backend/Dockerfile
- frontend: https://github.com/aelassas/bookcars/blob/main/frontend/Dockerfile
- compose: https://github.com/aelassas/bookcars/blob/main/docker-compose.yml

**Comment by beankylla** [comment]
Thanks, sorry for not seeing this!
