### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by team-boo** [aelassas/bookcars#47]
I have an error that i cant understand why is happening

"1388 timing reify:rollback:retireShallow Completed in 237ms
1389 timing command:install Completed in 5714ms
1390 verbose stack Error: ENOTEMPTY: directory not empty, rename '/opt/bookcars/frontend/node_modules/ajv-formats' -> '/opt/bookcars/frontend/node_modules/.ajv-formats-RUOYCnfG'
1391 verbose cwd /opt/bookcars/frontend
1392 verbose Linux 6.1.0-17-cloud-amd64
1393 verbose node v18.19.0
1394 verbose npm  v9.2.0
1395 error code ENOTEMPTY
1396 error syscall rename
1397 error path /opt/bookcars/frontend/node_modules/ajv-formats
1398 error dest /opt/bookcars/frontend/node_modules/.ajv-formats-RUOYCnfG
1399 error errno -39
1400 error ENOTEMPTY: directory not empty, rename '/opt/bookcars/frontend/node_modules/ajv-formats' -> '/opt/bookcars/frontend/node_modules/.ajv-formats-RUOYCnfG'
1401 verbose exit -39
1402 timing npm Completed in 5788ms
1403 verbose unfinished npm timer reify 1713129007276
1404 verbose unfinished npm timer reify:retireShallow 1713129012202
1405 verbose code -39
1406 error A complete log of this run can be found in:"

**Comment by aelassas** [comment]
Are you using the latest version?

Have you tried removing `node_modules` and running npm install:
```shell
cd /opt/bookcars/frontend
rm -rf node_modules
npm install
```

**Comment by team-boo** [comment]
I did what you said but nothing changed.

How to have apache2 with virtualmin and not nginx?

Thank you.

**Comment by aelassas** [comment]
Where did this package jv-formats come from? I am not using it in the frontend. Did you add it yourself?

Regarding apache2 with virtualmin, you need to build the frontend with `npm run build`, copy the content of `build` folder somewhere and configure the frontend on apache2 yourself.

**Comment by team-boo** [comment]
I have more logs here

https://pastebin.com/R42AaDkA

**Comment by team-boo** [comment]
Yes i have 1GB RAM on my VPS.

In the other VPS that i have plenty of RAM was not possible to install because CPU has not AVX and MONGODB cant work on CPU without AVX.

Thnx a lot for all.

**Comment by aelassas** [comment]
> MONGODB cant work on CPU without AVX.

You can use MongoDB Atlas and update `BC_DB_URI` in `api/.env`: https://www.mongodb.com/atlas/database
