### ISSUE TITLE
VPS HOWTO

### ISSUE THREAD

**Issue by team-boo** [aelassas/bookcars#48]
Hello,

Would be very important to have a install HOWTO for Apache with VPS.

I tried but was too complicated.

Thank you.

**Comment by team-boo** [comment]
I copied the content of frontend/build folder in /home/hostname/public_html/bookcars/frontend and backend/build folder in /home/hostname/public_html/bookcars/backend but apache didnt serve the files.

Of course i changed paths on api/.env from /var/www/bookcars/ to home/hostname/public_html/bookcars.

**Comment by team-boo** [comment]
Development has an error like 

"Uncaught runtime errors:
ERROR
Network Error
AxiosError@http://ip:3001/static/js/bundle.js:66971:18
handleError@http://ip:3001/static/js/bundle.js:66335:14
"

**Comment by aelassas** [comment]
Hi @team-boo 

I have written a tutorial on how to install BookCars on a VPS running under Ubuntu 22.04 with at least 512MB of RAM and one CPU with Apache as a web server and MongoDB Atlas free tier as database server: https://github.com/aelassas/bookcars/wiki/Installing-on-VPS

Follow the steps described in this walkthrough and it should work fine.

Let me know if face any issue.

Cheers,

**Comment by team-boo** [comment]
Hello,

Nice!!

When i insert database i have this 

"./mongorestore --verbose --drop --gzip --uri="mongodb://admin:password@127.0.0.1:27017/bookcars?authSource=admin&appName=bookcars" --nsInclude="bookcars.*" --nsFrom="bookcars.*" --nsTo="bookcars.*" --archive=bookcars-db.zip
2024-04-19T09:30:28.483+0300    using write concern: &{majority false 0}
2024-04-19T09:30:28.537+0300    The --db and --collection flags are deprecated for this use-case; please use --nsInclude instead, i.e. with --nsInclude=${DATABASE}.${COLLECTION}
2024-04-19T09:30:28.538+0300    Failed: gzip: invalid header
2024-04-19T09:30:28.538+0300    0 document(s) restored successfully. 0 document(s) failed to restore."

Googling was unsuccessful.

**Comment by aelassas** [comment]
You need to unzip bookcars-db.zip and go to ./bookcars-db folder from a terminal (it should contain bookcars.gz file), then run the `mongorestore` command:
```shell
mongorestore --verbose --drop --gzip --uri="mongodb://admin:password@127.0.0.1:27017/bookcars?authSource=admin&appName=bookcars" --nsInclude="bookcars." --nsFrom="bookcars." --nsTo="bookcars.*" --archive=bookcars.gz
```

**Comment by team-boo** [comment]
Thnx a lot.

I still have always this 

"ERROR
Network Error
AxiosError@http://192.168.1.11:3002/static/js/bundle.js:66452:18
handleError@http://192.168.1.11:3002/static/js/bundle.js:65816:14
"

**Comment by aelassas** [comment]
> Network Error

Try the following GET request from a web browser: http://192.168.1.11:4002/api/locations/1/30/en

If it fails, this means that the API is not working.

> 192.168.1.11

This is a local IP, are you trying to install on a VPS or on a local server?

**Comment by team-boo** [comment]
Hello again,

I did all steps from your new VPS HOWTO but when i execute 

 "a2ensite bookcars-frontend.conf
ERROR: Site bookcars-frontend does not exist!"

I'm installing on a VPS that is created from Virtualmin.

I have checked all directories execute rights.

Thank you.

**Comment by aelassas** [comment]
Which version of Apache do you have:
```shell
apachectl -v
```
What is the content of `sites-enabled`:
```shell
ls -l /etc/apache2/sites-enabled/
```
And the content of `sites-available`:
```shell
ls -l /etc/apache2/sites-available/
```

**Comment by team-boo** [comment]
https://pastebin.com/wQytmKDP

Server version: Apache/2.4.57 (Debian)

Thank you.

**Comment by aelassas** [comment]
There is no `bookcars-frontend.conf` in `/etc/apache2/sites-available/`.

As stated in the walkthrough, you have to create `/etc/apache2/sites-available/bookcars-frontend.conf` with the following content:
```
<VirtualHost *:80>
 # The ServerName directive sets the request scheme, hostname and port that
 # the server uses to identify itself. This is used when creating
 # redirection URLs. In the context of virtual hosts, the ServerName
 # specifies what hostname must appear in the request's Host: header to
 # match this virtual host. For the default virtual host (this file) this
 # value is not decisive as it is used as a last resort host regardless.
 # However, you must set it for any further virtual host explicitly.
 #ServerName www.example.com

 ServerAdmin webmaster@localhost
 DocumentRoot /var/www/movinin/frontend

 Alias /cdn /var/www/cdn

 <Directory "/var/www/cdn">    
   allow from all
   order allow,deny
   AllowOverride All
 </Directory>

 <Directory "/var/www/movinin/frontend">
   RewriteEngine On
   # Don't rewrite files or directories
   RewriteCond %{REQUEST_FILENAME} -f [OR]
   RewriteCond %{REQUEST_FILENAME} -d
   RewriteRule ^ - [L]
   # Rewrite everything else to index.html to allow html5 state links
   RewriteRule ^ index.html [L]
 </Directory>

 # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
 # error, crit, alert, emerg.
 # It is also possible to configure the loglevel for particular
 # modules, e.g.
 #LogLevel info ssl:warn

 ErrorLog ${APACHE_LOG_DIR}/error.log
 CustomLog ${APACHE_LOG_DIR}/access.log combined

 # For most configuration files from conf-available/, which are
 # enabled or disabled at a global level, it is possible to
 # include a line for only one particular virtual host. For example the
 # following line enables the CGI configuration for this host only
 # after it has been globally disabled with "a2disconf".
 #Include conf-available/serve-cgi-bin.conf
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

Make sure that the port 80 is not used by another config in  `/etc/apache2/sites-enabled/`

Then run the following commands:
```shelll
sudo a2enmod rewrite
sudo systemctl restart apache2
sudo a2dissite 000-default.conf
sudo a2ensite bookcars-frontend.conf
sudo systemctl reload apache2
sudo systemctl status apache2
```

The frontend will be accessible from: http://\<VPS-IP\>

**Comment by team-boo** [comment]
All that vps that are running are running from port 80 and 443 so i cant use port 80

How to install and work with https://domain.gg:3001 or https://domain.gg

**Comment by team-boo** [comment]
I tried to use dev version as https://domain.gg/  but i had problem there too.

This path /var/www/bookcars must run as /home/domain/public_html/bookcars  and 

/var/www/cdn  as /home/domain/public_html/cdn if possible.

**Comment by aelassas** [comment]
Ok, So proceed as follow:

1. Create  `/home/domain/public_html/cdn/bookcars` and add permissions:
    ````shell
    sudo mkdir -p /home/domain/public_html/cdn/bookcars
    sudo chown -R $USER:$USER /home/domain/public_html/cdn/bookcars
    ````
2. In `/opt/bookcars/api/.env`, Replace `/var/www/cdn` by `/home/domain/public_html/cdn` and restart `bookcars` service:
    ```shell
    sudo systemctl restart bookcars.service
    sudo systemctl status bookcars.service
    ```
    Check that `bookcars` service is running with the following URL: http://domain.gg:4002/api/locations/1/30/en
4. If you used demo database, copy the content of `bookcars-db/demo` in `/home/domain/public_html/cdn`
5. Build the frontend on your desktop PC and copy the folder `frontend/build` to `/opt/bookcars/frontend`
6. Copy the content of `/opt/bookcars/frontend/build/` in`/home/domain/public_html/bookcars/frontend`
7. We will use the port 3002 for the frontend since the port 80 is already in use. Create `/etc/apache2/sites-available/bookcars-frontend.conf` with the following content (You should check and update `/home/domain` path in the config):
    ```
    Listen 3002
    <VirtualHost *:3002>
     # The ServerName directive sets the request scheme, hostname and port that
     # the server uses to identify itself. This is used when creating
     # redirection URLs. In the context of virtual hosts, the ServerName
     # specifies what hostname must appear in the request's Host: header to
     # match this virtual host. For the default virtual host (this file) this
     # value is not decisive as it is used as a last resort host regardless.
     # However, you must set it for any further virtual host explicitly.
     #ServerName www.example.com

     ServerAdmin webmaster@localhost
     DocumentRoot /home/domain/public_html/bookcars/frontend

     Alias /cdn /home/domain/public_html/cdn

     <Directory "/home/domain/public_html/cdn">    
       allow from all
       order allow,deny
       AllowOverride All
     </Directory>

     <Directory "/home/domain/public_html/bookcars/frontend">
       RewriteEngine On
       # Don't rewrite files or directories
       RewriteCond %{REQUEST_FILENAME} -f [OR]
       RewriteCond %{REQUEST_FILENAME} -d
       RewriteRule ^ - [L]
       # Rewrite everything else to index.html to allow html5 state links
       RewriteRule ^ index.html [L]
     </Directory>

     # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
     # error, crit, alert, emerg.
     # It is also possible to configure the loglevel for particular
     # modules, e.g.
     #LogLevel info ssl:warn

     ErrorLog ${APACHE_LOG_DIR}/error.log
     CustomLog ${APACHE_LOG_DIR}/access.log combined

     # For most configuration files from conf-available/, which are
     # enabled or disabled at a global level, it is possible to
     # include a line for only one particular virtual host. For example the
     # following line enables the CGI configuration for this host only
     # after it has been globally disabled with "a2disconf".
     #Include conf-available/serve-cgi-bin.conf
    </VirtualHost>

    # vim: syntax=apache ts=4 sw=4 sts=4 sr noet
    ```
7. run the following commands:
  ```shelll
  sudo a2enmod rewrite
  sudo systemctl restart apache2
  sudo a2ensite bookcars-frontend.conf
  sudo systemctl reload apache2
  sudo systemctl status apache2
  ```

The frontend will be accessible from: http://domain.gg:3002

**Comment by team-boo** [comment]
Api works but 

"[Fri Apr 19 21:36:35.350776 2024] [autoindex:error] [pid 298093:tid 140441848628928] [client :33464] AH01276: Cannot serve directory /home/domain/public_html/: No matching DirectoryIndex (index.php,index.php4,index.php5,index.htm,index.html) found, and server-generated directory index forbidden by Options directive"

I inserted your apache directives nothing else.

**Comment by aelassas** [comment]
Why /var/www/bookcars/frontend does not work? What error do you get when
you use it?

**Comment by team-boo** [comment]
i thought that was most clean solution for vps to use folders that are on /home/domain because /var/www/bookcars/frontend was controlled from root

**Comment by aelassas** [comment]
The errors you are getting are specific to virtualmin. You may find help
on: https://forum.virtualmin.com/

**Comment by team-boo** [comment]
Virtualmin is a frontend for Apache in this case.

Thnx anyway

**Comment by team-boo** [comment]
I used dev version with npm install &&  npm start from domain/public_html/bookcars/folder
but i have always "ERROR
Network Error
AxiosError@http://domain:3001/static/js/bundle.js:66972:18
handleError@http://domain:3001/static/js/bundle.js:66336:14
"
for frontend and backend.

Fronted page is working but i cant sign in or sign up.
Backend has open port but empty page.
Database is working together with bookcars service.

How to run dev version from public_html folder and to use default https.

When i use https://domain i cant

**Comment by aelassas** [comment]
What is the result of the following query: http://domain:4002/api/locations/1/30/en

**Comment by team-boo** [comment]
![Screenshot_2024-04-21_15-33-17](https://github.com/aelassas/bookcars/assets/150141532/6a8e17f1-f358-47fc-9586-6bf164647f1c)

**Comment by aelassas** [comment]
Did you set the following setting in backend/.env and frontend/.env:
```
REACT_APP_BC_API_HOST=http://domain:4002
```

**Comment by team-boo** [comment]
yes

**Comment by aelassas** [comment]
Let's stick with the frontend first. Open http://domain:3002 and go to Chrome Dev Tools > Network Tab, reload the page, click on sign-out xhr, and show me the error you are getting.

**Comment by aelassas** [comment]
In api/.env, did you set:
```
BC_AUTH_COOKIE_DOMAIN=domain
```

Are the frontend and the api hosted on the same server?

**Comment by team-boo** [comment]
yes for both questions

**Comment by aelassas** [comment]
On Chrome Dev Tools, go to Network Tab, click on sign-out xhr and show me **Request URL** in Headers Tab.

**Comment by team-boo** [comment]
![Screenshot_2024-04-21_16-35-37](https://github.com/aelassas/bookcars/assets/150141532/b2f7fb67-df2f-4354-9037-f440fed92b24)

**Comment by aelassas** [comment]
When you hover sign-out xhr, what URL do you get?

**Comment by team-boo** [comment]
"Nothing to see here!
[Go to the home page](http://domain.:3002/)"

**Comment by aelassas** [comment]
No, in Network tab click on sign-out xhr and show me **Request URL** value.

**Comment by team-boo** [comment]
"Accept:
application/json, text/plain, */*
Content-Type:
application/x-www-form-urlencoded
Referer:
http://domain.:3002/
Sec-Ch-Ua:
"Not_A Brand";v="8", "Chromium";v="120"
Sec-Ch-Ua-Mobile:
?0
Sec-Ch-Ua-Platform:
"Linux"
User-Agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

"Request URL:
http://127.0.0.1:4002/api/sign-out
Referrer Policy:
strict-origin-when-cross-origin"

**Comment by aelassas** [comment]
You didn't set `REACT_APP_BC_API_HOST` to `http://domain:4002`. That's why you are getting this error. The frontend can't reach the api.

Replace `http://127.0.0.1:4002` by `http://domain:4002`, then run `npm start` and test again.

**Comment by team-boo** [comment]
i had this before as http://domain:4002

**Comment by aelassas** [comment]
Try to clear cache (Ctrl+F5) and show me the **Request URL** of sign-out xhr again.

**Comment by team-boo** [comment]
Request URL:
http://domain:4002/api/sign-out
Referrer Policy:
strict-origin-when-cross-origin

**Comment by aelassas** [comment]
Now, request url is valid. Are you still getting the error on the frontend?

**Comment by team-boo** [comment]
yes

**Comment by aelassas** [comment]
The error says that the frontend can't reach the api.  Try the following query from the pc from which you are trying to access the frontend and show me its result: http://domain:4002/api/locations/1/30/en

**Comment by team-boo** [comment]
Now this link http://domain:4002/api/locations/1/30/en that was working before is not answering from other pc 

i check frontend and is still working so is not a fail2ban or iptable issue.

really i dont now what is happening.

i can give you real access on my VPS if you want.

**Comment by aelassas** [comment]
Check that bookcars service is running: `sudo systemctl status bookcars`

Do you have firewall enabled on your vps?

**Comment by team-boo** [comment]
● bookcars.service - BookCars API
     Loaded: loaded (/etc/systemd/system/bookcars.service; enabled; preset: enabled)
     Active: active (running) since Sun 2024-04-21 16:21:44 EEST; 1h 39min ago
   Main PID: 263327 (npm start)
      Tasks: 31 (limit: 483558)
     Memory: 69.0M
        CPU: 30.938s
     CGroup: /system.slice/bookcars.service
             ├─263327 "npm start"
             ├─263345 sh -c "npm run build && node dist/src"
             └─263425 node dist/src

i have fail2ban but frontend is working so smth else is happening

**Comment by team-boo** [comment]
i can give total control to VPS.Is good to test it because is linux and most important installs now are in linux

**Comment by aelassas** [comment]
Ok, you can find my email on my profile: https://github.com/aelassas

**Comment by team-boo** [comment]
yes

**Comment by aelassas** [comment]
I answered you.

**Comment by aelassas** [comment]
Hi, I am back.

I disabled HTTPS in bookcars service so we can test it. Can you restart it?

I will show you how to enable HTTPS later.
