### ISSUE TITLE
impossible de créer/modifier une nouvelle voiture

### ISSUE THREAD

**Issue by slachtar** [aelassas/bookcars#50]
Bonjour,
sur cette interface, impossible de créer ou modifier une voiture existante.
https://bookcars.v6.rocks:3001/cars
merci

**Comment by aelassas** [comment]
Oui, j'ai désactivé certaines fonctionnalités sur la demo car certaines
personnes uploadaient des images malsaines et changeaient les données de
démo avec des mauvaises valeurs.

**Comment by slachtar** [comment]
T’as raison
