### ISSUE TITLE
bookcars.service - BookCars API (Failed to start)

### ISSUE THREAD

**Issue by ogolafreeman** [aelassas/bookcars#51]
Hey team, I was trying to install the project on my local machine running Ubuntu 22.04.4, everything went well until the step where i have to check if the bookcars.service is active. I have tried to restart but i cant start the service. kindly help. am getting this error

× bookcars.service - BookCars API
     Loaded: loaded (/etc/systemd/system/bookcars.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2024-06-24 23:40:51 EAT; 15s ago
    Process: 40499 ExecStart=/usr/bin/npm start (code=exited, status=1/FAILURE)
   Main PID: 40499 (code=exited, status=1/FAILURE)
        CPU: 1.143s

Jun 24 23:40:51 OGOLA systemd[1]: bookcars.service: Failed with result 'exit-code'.
Jun 24 23:40:51 OGOLA systemd[1]: bookcars.service: Consumed 1.143s CPU time.
Jun 24 23:40:51 OGOLA systemd[1]: bookcars.service: Scheduled restart job, restart counter is at 5.
Jun 24 23:40:51 OGOLA systemd[1]: Stopped BookCars API.
Jun 24 23:40:51 OGOLA systemd[1]: bookcars.service: Consumed 1.143s CPU time.
Jun 24 23:40:51 OGOLA systemd[1]: bookcars.service: Start request repeated too quickly.
Jun 24 23:40:51 OGOLA systemd[1]: bookcars.service: Failed with result 'exit-code'.
Jun 24 23:40:51 OGOLA systemd[1]: Failed to start BookCars API.

**Comment by aelassas** [comment]
Can you check the logs:
cat /opt/bookcars/api/logs/all.log

If there are no logs, try these commands to see what's wrong:
cd /opt/bookcars/api/
npm install
npm start

Le lun. 24 juin 2024, 21:49, Jacktone Okwemba ***@***.***> a
écrit :

**Comment by aelassas** [comment]
@ogolafreeman Have you tried my instructions?
